/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/browser-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBrowserConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchAsset"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/assets/{asset_id}:quarantine": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quarantineAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/assets/{asset_id}:retire": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retireAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/asset-relations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get: operations["listAssetRelations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/service-asset-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        get: operations["listServiceAssetBindings"];
        put?: never;
        post: operations["createServiceAssetBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/environments/{environment_id}/service-asset-bindings/{binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                binding_id: components["parameters"]["BindingID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteServiceAssetBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        get: operations["listAssetSources"];
        put?: never;
        post: operations["createAssetSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get: operations["getAssetSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAssetSourceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}/revisions/{revision}:validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateAssetSourceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}/revisions/{revision}:publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishAssetSourceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}:disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableAssetSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}:sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncAssetSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAssetSourceImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-sources/{source_id}/ingestion-batches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAssetSourceIngestionBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-source-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get: operations["getAssetSourceRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        get: operations["listAssetConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/asset-conflicts/{conflict_id}:resolve": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                conflict_id: components["parameters"]["ConflictID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAssetConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        TraceID: string;
        Digest: string;
        /** Format: uuid */
        NullableUUID: string | null;
        NullableDigest: string | null;
        /** Format: date-time */
        NullableDateTime: string | null;
        NullableSafeText: string | null;
        /** @enum {string} */
        EffectiveAction: "CREATE_ASSET" | "EDIT_GOVERNANCE" | "QUARANTINE" | "RETIRE" | "CREATE_BINDING" | "DELETE_BINDING" | "RESOLVE_CONFLICT" | "CREATE_SOURCE" | "CREATE_SOURCE_REVISION" | "VALIDATE_SOURCE_REVISION" | "PUBLISH_SOURCE_REVISION" | "DISABLE_SOURCE" | "SYNC_SOURCE" | "IMPORT_CSV";
        /** @enum {string} */
        AssetKind: "SERVICE" | "LINUX_VM" | "WINDOWS_VM" | "BARE_METAL_HOST" | "KUBERNETES_CLUSTER" | "KUBERNETES_NAMESPACE" | "KUBERNETES_WORKLOAD" | "DATABASE_INSTANCE" | "DATABASE" | "METRICS_SOURCE" | "LOG_SOURCE" | "TRACE_SOURCE" | "AWX_INVENTORY" | "ARGO_APPLICATION" | "CI_PIPELINE" | "GIT_REPOSITORY" | "CLOUD_RESOURCE";
        /** @enum {string} */
        AssetLifecycle: "DISCOVERED" | "ACTIVE" | "STALE" | "QUARANTINED" | "RETIRED";
        /** @enum {string} */
        MappingStatus: "EXACT" | "AMBIGUOUS" | "UNRESOLVED";
        /** @enum {string} */
        Criticality: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** @enum {string} */
        DataClassification: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED";
        /**
         * @default display_name_asc
         * @enum {string}
         */
        AssetSort: "display_name_asc" | "last_observed_at_desc";
        /** @enum {string} */
        RelationshipType: "RUNS_ON" | "CONTAINS" | "DEPENDS_ON" | "MONITORED_BY" | "LOGS_TO" | "TRACES_TO" | "DELIVERED_BY" | "MANAGED_BY" | "PRIMARY_RUNTIME_FOR";
        /** @enum {string} */
        RelationshipStatus: "ACTIVE" | "INACTIVE";
        /** @enum {string} */
        BindingRole: "PRIMARY_RUNTIME" | "DEPENDENCY" | "OBSERVABILITY_SOURCE" | "DELIVERY_TARGET" | "MANAGED_TARGET";
        /** @enum {string} */
        BindingStatus: "ACTIVE" | "INACTIVE";
        /** @enum {string} */
        Provenance: "MANUAL" | "DISCOVERED" | "MERGE_DECISION";
        /** @enum {string} */
        SourceKind: "MANUAL" | "CSV_IMPORT" | "CONTROL_PLANE_API" | "EXTERNAL_CMDB" | "VSPHERE" | "PROXMOX" | "OPENSTACK" | "CLOUD_PROVIDER" | "KUBERNETES_OPERATOR" | "AWX_INVENTORY";
        /** @enum {string} */
        SourceStatus: "ACTIVE" | "PAUSED" | "DEGRADED" | "DISABLED";
        /** @enum {string} */
        SourceGateStatus: "UNAVAILABLE" | "VALIDATING" | "AVAILABLE" | "DEGRADED" | "SUSPENDED";
        /** @enum {string} */
        SourceRevisionStatus: "DRAFT" | "VALIDATING" | "VALIDATED" | "REJECTED" | "PUBLISHED" | "SUPERSEDED";
        /** @enum {string} */
        SourceSyncMode: "MANUAL" | "ON_DEMAND" | "SCHEDULED";
        /** @enum {string} */
        RunKind: "VALIDATION" | "DISCOVERY" | "CSV_IMPORT" | "API_INGESTION" | "MANUAL_MUTATION";
        /** @enum {string} */
        RunStatus: "QUEUED" | "DELAYED" | "RUNNING" | "FINALIZING" | "SUCCEEDED" | "PARTIAL" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        RunStage: "WAITING" | "DELAYED" | "VALIDATING" | "READING" | "NORMALIZING" | "APPLYING" | "CLEANING_UP" | "COMPLETED";
        /** @enum {string} */
        TriggerType: "HUMAN" | "API" | "SCHEDULED";
        /** @enum {string} */
        CredentialCleanupStatus: "NOT_OPENED" | "PENDING" | "REVOKED" | "NO_CREDENTIAL" | "UNCERTAIN";
        /** @enum {string} */
        ConflictStatus: "OPEN" | "RESOLVED" | "REJECTED";
        /** @enum {string} */
        ConflictResolution: "CONFIRM_EXACT" | "REJECT_CANDIDATE" | "KEEP_UNRESOLVED" | "QUARANTINE_ASSET";
        /** @enum {string} */
        FieldOwnership: "SOURCE" | "GOVERNANCE" | "MERGE_DECISION";
        BrowserConfig: {
            oidc: components["schemas"]["BrowserOIDCConfig"];
            /** @constant */
            api_base_path: "/api/v1";
            build: components["schemas"]["BrowserBuildInfo"];
        };
        BrowserOIDCConfig: {
            /** Format: uri */
            url: string;
            realm: string;
            /** @constant */
            client_id: "control-plane-web";
        };
        BrowserBuildInfo: {
            version: string;
            commit: string;
            contract_digest: string;
        };
        Session: {
            subject: string;
            username: string;
            roles: ("VIEWER" | "SRE" | "SERVICE_OWNER" | "APPROVER" | "AUDITOR" | "ADMIN")[];
            workspace_ids: string[];
            environment_ids: string[];
            service_ids: string[];
            /** Format: date-time */
            authenticated_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        OverviewImplementationState: "NOT_STARTED" | "UNAVAILABLE" | "PARTIAL" | "AVAILABLE" | "DEGRADED" | "SUSPENDED";
        /** @enum {string} */
        OverviewSectionCode: "NOT_IMPLEMENTED" | "MODULE_UNAVAILABLE" | "AGGREGATE_PARTIAL" | "READY" | "STALE_EVIDENCE" | "SUSPENDED";
        /** @enum {string} */
        OverviewFeature: "ASSETS" | "SOURCES" | "CONNECTIONS" | "INVESTIGATIONS" | "ACTIONS" | "RELEASES";
        /** @enum {string} */
        OverviewEffectiveAction: "VIEW_ASSETS" | "VIEW_SOURCES" | "VIEW_CONNECTIONS" | "VIEW_INVESTIGATIONS" | "VIEW_ACTIONS" | "VIEW_RELEASES";
        /** @enum {string} */
        OverviewWorkQueueKey: "OPEN_CONFLICTS" | "STALE_ASSETS" | "UNAVAILABLE_SOURCES" | "DEGRADED_SOURCES";
        OverviewScope: {
            workspace_id: components["schemas"]["UUID"];
            environment_id: components["schemas"]["UUID"];
        };
        OverviewStateCount: {
            state: string;
            /** Format: int64 */
            count: number;
        };
        OverviewProviderGateSummary: {
            provider_kind: string;
            gate_status: components["schemas"]["SourceGateStatus"];
            /** Format: int64 */
            source_count: number;
            evidence_at: components["schemas"]["NullableDateTime"];
        };
        OverviewAssetFacts: {
            /** Format: int64 */
            total: number;
            lifecycles: components["schemas"]["OverviewStateCount"][];
            mapping_statuses: components["schemas"]["OverviewStateCount"][];
            /** Format: int64 */
            stale_count: number;
            oldest_stale_at: components["schemas"]["NullableDateTime"];
            /** Format: int64 */
            open_conflict_count: number;
        };
        OverviewSourceFacts: {
            /** Format: int64 */
            total: number;
            statuses: components["schemas"]["OverviewStateCount"][];
            revision_statuses: components["schemas"]["OverviewStateCount"][];
            gate_statuses: components["schemas"]["OverviewStateCount"][];
            run_statuses: components["schemas"]["OverviewStateCount"][];
            /** Format: int64 */
            backpressured_count: number;
            provider_gates: components["schemas"]["OverviewProviderGateSummary"][];
        };
        OverviewSection: {
            state: components["schemas"]["OverviewImplementationState"];
            code: components["schemas"]["OverviewSectionCode"];
            /** Format: date-time */
            observed_at: string;
            asset_facts: components["schemas"]["OverviewAssetFacts"] | null;
            source_facts: components["schemas"]["OverviewSourceFacts"] | null;
        };
        OverviewSections: {
            ASSETS: components["schemas"]["OverviewSection"];
            SOURCES: components["schemas"]["OverviewSection"];
            CONNECTIONS: components["schemas"]["OverviewSection"];
            INVESTIGATIONS: components["schemas"]["OverviewSection"];
            ACTIONS: components["schemas"]["OverviewSection"];
            RELEASES: components["schemas"]["OverviewSection"];
        };
        OverviewWorkQueue: {
            key: components["schemas"]["OverviewWorkQueueKey"];
            section: components["schemas"]["OverviewFeature"];
            state: components["schemas"]["OverviewImplementationState"];
            /** Format: int64 */
            count: number | null;
        };
        OverviewSnapshot: {
            scope: components["schemas"]["OverviewScope"];
            /** Format: date-time */
            generated_at: string;
            sections: components["schemas"]["OverviewSections"];
            work_queues: components["schemas"]["OverviewWorkQueue"][];
            effective_actions: components["schemas"]["OverviewEffectiveAction"][];
        };
        PageMeta: {
            next_cursor: string | null;
        };
        Label: {
            key: string;
            value: string;
        };
        SourceReference: {
            id: components["schemas"]["UUID"];
            name: string;
            kind: components["schemas"]["SourceKind"];
        };
        ServiceReference: {
            id: components["schemas"]["UUID"];
            name: string;
            role: components["schemas"]["BindingRole"];
        };
        ConnectionSummary: {
            /** @constant */
            status: "NOT_CONFIGURED";
        };
        CapabilitySummary: {
            /** @constant */
            status: "NOT_CONFIGURED";
            /** Format: int64 */
            count: number;
        };
        AssetSummary: {
            id: components["schemas"]["UUID"];
            environment_id: components["schemas"]["UUID"];
            display_name: string;
            external_id: string;
            kind: components["schemas"]["AssetKind"];
            provider_kind: string;
            source: components["schemas"]["SourceReference"];
            service_summaries: components["schemas"]["ServiceReference"][];
            mapping_status: components["schemas"]["MappingStatus"];
            lifecycle: components["schemas"]["AssetLifecycle"];
            owner_group: components["schemas"]["NullableSafeText"];
            criticality: components["schemas"]["Criticality"];
            data_classification: components["schemas"]["DataClassification"];
            labels: components["schemas"]["Label"][];
            connection_summary: components["schemas"]["ConnectionSummary"];
            capability_summary: components["schemas"]["CapabilitySummary"];
            /** Format: date-time */
            last_observed_at: string;
            /** Format: int64 */
            version: number;
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        FieldProvenance: {
            field_code: string;
            source_id: components["schemas"]["UUID"];
            provider_kind: string;
            /** Format: int64 */
            source_revision: number;
            /** Format: date-time */
            observed_at: string;
            provider_path_code: string;
            /** Format: int32 */
            confidence: number;
            ownership: components["schemas"]["FieldOwnership"];
        };
        RelationCounts: {
            /** Format: int64 */
            incoming: number;
            /** Format: int64 */
            outgoing: number;
        };
        AssetDetail: {
            id: components["schemas"]["UUID"];
            environment_id: components["schemas"]["UUID"];
            display_name: string;
            external_id: string;
            kind: components["schemas"]["AssetKind"];
            provider_kind: string;
            source: components["schemas"]["SourceReference"];
            service_summaries: components["schemas"]["ServiceReference"][];
            mapping_status: components["schemas"]["MappingStatus"];
            lifecycle: components["schemas"]["AssetLifecycle"];
            owner_group: components["schemas"]["NullableSafeText"];
            criticality: components["schemas"]["Criticality"];
            data_classification: components["schemas"]["DataClassification"];
            labels: components["schemas"]["Label"][];
            connection_summary: components["schemas"]["ConnectionSummary"];
            capability_summary: components["schemas"]["CapabilitySummary"];
            /** Format: date-time */
            last_observed_at: string;
            /** Format: int64 */
            version: number;
            effective_actions: components["schemas"]["EffectiveAction"][];
            field_provenance: components["schemas"]["FieldProvenance"][];
            relation_counts: components["schemas"]["RelationCounts"];
        };
        AssetPage: {
            items: components["schemas"]["AssetSummary"][];
            page: components["schemas"]["PageMeta"];
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        CreateAssetRequest: {
            source_id: components["schemas"]["UUID"];
            kind: components["schemas"]["AssetKind"];
            external_id: string;
            display_name: string;
            owner_group: components["schemas"]["NullableSafeText"];
            criticality: components["schemas"]["Criticality"];
            data_classification: components["schemas"]["DataClassification"];
            labels: components["schemas"]["Label"][];
        };
        PatchAssetRequest: {
            display_name: string;
            owner_group: components["schemas"]["NullableSafeText"];
            criticality: components["schemas"]["Criticality"];
            data_classification: components["schemas"]["DataClassification"];
            labels: components["schemas"]["Label"][];
        };
        TransitionAssetRequest: {
            reason_code: string;
        };
        MutationReceipt: {
            audit_id: components["schemas"]["UUID"];
            trace_id: components["schemas"]["TraceID"];
            idempotent_replay: boolean;
        };
        AssetMutationResult: {
            asset: components["schemas"]["AssetDetail"];
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        AssetRelationSummary: {
            id: components["schemas"]["UUID"];
            source_environment_id: components["schemas"]["UUID"];
            target_environment_id: components["schemas"]["UUID"];
            source_asset_id: components["schemas"]["UUID"];
            target_asset_id: components["schemas"]["UUID"];
            type: components["schemas"]["RelationshipType"];
            status: components["schemas"]["RelationshipStatus"];
            provenance: components["schemas"]["Provenance"];
            source_id: components["schemas"]["UUID"];
            /** Format: int64 */
            source_revision: number;
            last_run_id: components["schemas"]["UUID"];
            /** Format: int64 */
            last_page_sequence: number;
            /** Format: int64 */
            accepted_checkpoint_version: number;
            /** Format: int64 */
            run_fence_epoch: number;
            provider_version_sha256: components["schemas"]["Digest"];
            relation_fact_sha256: components["schemas"]["Digest"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            updated_at: string;
        };
        AssetRelationPage: {
            items: components["schemas"]["AssetRelationSummary"][];
            page: components["schemas"]["PageMeta"];
        };
        ServiceAssetBindingSummary: {
            id: components["schemas"]["UUID"];
            environment_id: components["schemas"]["UUID"];
            service_id: components["schemas"]["UUID"];
            asset_id: components["schemas"]["UUID"];
            role: components["schemas"]["BindingRole"];
            /** @constant */
            mapping_status: "EXACT";
            provenance: components["schemas"]["Provenance"];
            status: components["schemas"]["BindingStatus"];
            /** Format: int64 */
            version: number;
            etag: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        ServiceAssetBindingPage: {
            items: components["schemas"]["ServiceAssetBindingSummary"][];
            page: components["schemas"]["PageMeta"];
        };
        CreateServiceAssetBindingRequest: {
            service_id: components["schemas"]["UUID"];
            asset_id: components["schemas"]["UUID"];
            role: components["schemas"]["BindingRole"];
            reason_code: string;
        };
        DeleteServiceAssetBindingRequest: {
            reason_code: string;
        };
        ServiceAssetBindingMutationResult: {
            binding: components["schemas"]["ServiceAssetBindingSummary"];
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        CreateAssetSourceRequest: {
            name: string;
            source_profile_id: string;
            authority_environment_ids: components["schemas"]["UUID"][];
        };
        CreateAssetSourceRevisionRequest: {
            source_profile_id: string;
            authority_environment_ids: components["schemas"]["UUID"][];
            change_reason_code: string;
        };
        SourceReasonRequest: {
            reason_code: string;
        };
        EmptySourceRequest: Record<string, never>;
        CreateAssetSourceImportRequest: {
            /** Format: binary */
            file: string;
            /** Format: binary */
            detached_signature: string;
        };
        SourceRunCounts: {
            /** Format: int64 */
            observed: number;
            /** Format: int64 */
            created: number;
            /** Format: int64 */
            changed: number;
            /** Format: int64 */
            unchanged: number;
            /** Format: int64 */
            conflicts: number;
            /** Format: int64 */
            missing: number;
            /** Format: int64 */
            stale: number;
            /** Format: int64 */
            restored: number;
            /** Format: int64 */
            tombstoned: number;
            /** Format: int64 */
            rejected: number;
        };
        AssetSourceSummary: {
            id: components["schemas"]["UUID"];
            name: string;
            kind: components["schemas"]["SourceKind"];
            provider_kind: string;
            status: components["schemas"]["SourceStatus"];
            gate_status: components["schemas"]["SourceGateStatus"];
            gate_reason_code: string | null;
            /** Format: int64 */
            gate_revision: number;
            /** Format: int64 */
            published_revision: number | null;
            published_revision_digest: components["schemas"]["NullableDigest"];
            checkpoint_sha256: components["schemas"]["NullableDigest"];
            /** Format: int64 */
            checkpoint_version: number;
            last_success_run_id: components["schemas"]["NullableUUID"];
            last_success_at: components["schemas"]["NullableDateTime"];
            last_complete_snapshot_run_id: components["schemas"]["NullableUUID"];
            last_complete_snapshot_at: components["schemas"]["NullableDateTime"];
            current_run_counts: components["schemas"]["SourceRunCounts"] | null;
            last_run_counts: components["schemas"]["SourceRunCounts"] | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        SourceRevisionSummary: {
            /** Format: int64 */
            revision: number;
            status: components["schemas"]["SourceRevisionStatus"];
            profile_code: string;
            integration_id: components["schemas"]["NullableUUID"];
            sync_mode: components["schemas"]["SourceSyncMode"];
            credential_reference_id: components["schemas"]["NullableUUID"];
            trust_reference_id: components["schemas"]["NullableUUID"];
            network_policy_reference_id: components["schemas"]["NullableUUID"];
            authority_environment_ids: components["schemas"]["UUID"][];
            binding_digest: components["schemas"]["Digest"];
            source_definition_digest: components["schemas"]["Digest"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        AssetSourceDetail: {
            summary: components["schemas"]["AssetSourceSummary"];
            latest_revision: components["schemas"]["SourceRevisionSummary"];
            published_revision: components["schemas"]["SourceRevisionSummary"] | null;
        };
        AssetSourcePage: {
            items: components["schemas"]["AssetSourceSummary"][];
            page: components["schemas"]["PageMeta"];
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        AssetSourceRun: {
            id: components["schemas"]["UUID"];
            source_id: components["schemas"]["UUID"];
            /** Format: int64 */
            source_revision: number;
            source_revision_digest: components["schemas"]["Digest"];
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            stage: components["schemas"]["RunStage"];
            /** Format: date-time */
            stage_changed_at: string;
            trigger_type: components["schemas"]["TriggerType"];
            /** Format: int64 */
            gate_revision: number;
            /** Format: int64 */
            page_sequence: number;
            /** Format: int64 */
            relation_page_sequence: number;
            cursor_before_sha256: components["schemas"]["NullableDigest"];
            cursor_after_sha256: components["schemas"]["NullableDigest"];
            /** Format: int64 */
            checkpoint_version: number;
            /** Format: date-time */
            not_before: string;
            final_page: boolean;
            complete_snapshot: boolean;
            effective_complete_snapshot: boolean;
            /** @enum {string|null} */
            work_result_kind: "DATA_PROJECTION" | "VALIDATION_PROOF" | "FAILURE_INTENT" | null;
            /** @enum {string|null} */
            work_result_status: "SUCCEEDED" | "PARTIAL" | "FAILED" | null;
            work_result_digest: components["schemas"]["NullableDigest"];
            work_result_recorded_at: components["schemas"]["NullableDateTime"];
            /** @enum {string|null} */
            validation_outcome: "SUCCEEDED" | "FAILED" | null;
            validation_proof_digest: components["schemas"]["NullableDigest"];
            credential_cleanup_status: components["schemas"]["CredentialCleanupStatus"];
            counts: components["schemas"]["SourceRunCounts"];
            failure_code: string | null;
            trace_id: string | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            started_at: components["schemas"]["NullableDateTime"];
            heartbeat_at: components["schemas"]["NullableDateTime"];
            completed_at: components["schemas"]["NullableDateTime"];
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        AssetSourceRevisionMutationResult: {
            source: components["schemas"]["AssetSourceSummary"];
            revision: components["schemas"]["SourceRevisionSummary"];
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        AssetSourceMutationResult: {
            source: components["schemas"]["AssetSourceSummary"];
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        AssetSourceRunMutationResult: {
            source: components["schemas"]["AssetSourceSummary"];
            revision: components["schemas"]["SourceRevisionSummary"];
            run: components["schemas"]["AssetSourceRun"];
            operation_id: components["schemas"]["UUID"];
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        ConflictAssetReference: {
            id: components["schemas"]["UUID"];
            display_name: string;
            kind: components["schemas"]["AssetKind"];
            lifecycle: components["schemas"]["AssetLifecycle"];
        };
        ConflictServiceReference: {
            id: components["schemas"]["UUID"];
            name: string;
        };
        ConflictObservationReference: {
            id: components["schemas"]["UUID"];
            source_id: components["schemas"]["UUID"];
            /** Format: int64 */
            source_revision: number;
            /** Format: date-time */
            observed_at: string;
        };
        ConflictImpactCounts: {
            /** Format: int64 */
            asset_active_bindings: number;
            /** Format: int64 */
            asset_active_relationships: number;
            /** Format: int64 */
            candidate_asset_active_bindings: number;
            /** Format: int64 */
            candidate_asset_active_relationships: number;
            /** Format: int64 */
            candidate_service_active_bindings: number;
        };
        AssetConflictDetail: {
            id: components["schemas"]["UUID"];
            environment_id: components["schemas"]["UUID"];
            asset: components["schemas"]["ConflictAssetReference"];
            candidate_asset: components["schemas"]["ConflictAssetReference"] | null;
            candidate_service: components["schemas"]["ConflictServiceReference"] | null;
            source_id: components["schemas"]["UUID"];
            observation: components["schemas"]["ConflictObservationReference"];
            type: string;
            field_name: string;
            existing_value_sha256: components["schemas"]["Digest"];
            candidate_value_sha256: components["schemas"]["Digest"];
            status: components["schemas"]["ConflictStatus"];
            /** @enum {string|null} */
            resolution: "CONFIRM_EXACT" | "REJECT_CANDIDATE" | "KEEP_UNRESOLVED" | "QUARANTINE_ASSET" | null;
            resolution_reason_code: string | null;
            resolved_at: components["schemas"]["NullableDateTime"];
            impact_counts: components["schemas"]["ConflictImpactCounts"];
            /** Format: int64 */
            version: number;
            etag: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            effective_actions: components["schemas"]["EffectiveAction"][];
        };
        AssetConflictSummary: components["schemas"]["AssetConflictDetail"];
        AssetConflictPage: {
            items: components["schemas"]["AssetConflictSummary"][];
            page: components["schemas"]["PageMeta"];
        };
        ResolveAssetConflictRequest: components["schemas"]["ConfirmExactConflictRequest"] | components["schemas"]["RejectCandidateConflictRequest"] | components["schemas"]["KeepUnresolvedConflictRequest"] | components["schemas"]["QuarantineConflictAssetRequest"];
        ConfirmExactConflictRequest: {
            /** @constant */
            resolution: "CONFIRM_EXACT";
            service_id: components["schemas"]["UUID"];
            binding_role: components["schemas"]["BindingRole"];
            reason_code: string;
        };
        RejectCandidateConflictRequest: {
            /** @constant */
            resolution: "REJECT_CANDIDATE";
            reason_code: string;
        };
        KeepUnresolvedConflictRequest: {
            /** @constant */
            resolution: "KEEP_UNRESOLVED";
            reason_code: string;
        };
        QuarantineConflictAssetRequest: {
            /** @constant */
            resolution: "QUARANTINE_ASSET";
            reason_code: string;
        };
        AssetConflictMutationResult: {
            conflict: components["schemas"]["AssetConflictDetail"];
            binding: components["schemas"]["ServiceAssetBindingSummary"] | null;
            mutation_receipt: components["schemas"]["MutationReceipt"];
        };
        Problem: {
            /** @constant */
            type: "about:blank";
            title: string;
            status: number;
            code: string;
            detail: string;
            trace_id: components["schemas"]["TraceID"];
        };
    };
    responses: {
        /** @description Public browser bootstrap metadata. */
        BrowserConfigOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BrowserConfig"];
            };
        };
        /** @description Current authenticated browser session. */
        SessionOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Scope-safe governed operations readiness snapshot. */
        OverviewOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OverviewSnapshot"];
            };
        };
        /** @description Scoped asset page. */
        AssetPageOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetPage"];
            };
        };
        /** @description Safe asset detail. */
        AssetDetailOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetDetail"];
            };
        };
        /** @description Asset created through the governed MANUAL path. */
        AssetCreated: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                Location: components["headers"]["Location"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetMutationResult"];
            };
        };
        /** @description Governed asset mutation result. */
        AssetMutationOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetMutationResult"];
            };
        };
        /** @description Scoped relationship page. */
        AssetRelationPageOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetRelationPage"];
            };
        };
        /** @description Scoped Service binding page. */
        ServiceAssetBindingPageOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServiceAssetBindingPage"];
            };
        };
        /** @description Service binding created. */
        ServiceAssetBindingCreated: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                Location: components["headers"]["Location"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServiceAssetBindingMutationResult"];
            };
        };
        /** @description Service binding is inactive; an identical replay returns the same receipt headers. */
        ServiceAssetBindingDeleted: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                "X-Audit-ID": components["headers"]["AuditID"];
                "X-Idempotent-Replay": components["headers"]["IdempotentReplay"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Scoped safe Source page. */
        AssetSourcePageOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourcePage"];
            };
        };
        /** @description Safe Source detail. */
        AssetSourceDetailOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceDetail"];
            };
        };
        /** @description Safe Source Run detail. */
        AssetSourceRunOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceRun"];
            };
        };
        /** @description Stable Source and immutable revision created atomically. */
        AssetSourceRevisionCreated: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                Location: components["headers"]["Location"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceRevisionMutationResult"];
            };
        };
        /** @description Governed Source revision mutation result. */
        AssetSourceRevisionMutationOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceRevisionMutationResult"];
            };
        };
        /** @description Governed stable Source mutation result. */
        AssetSourceMutationOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceMutationResult"];
            };
        };
        /** @description Synchronous terminal Source validation result. */
        AssetSourceRunMutationOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceRunMutationResult"];
            };
        };
        /** @description Durable Source Run accepted; a currently unimplemented runtime returns Problem503 instead. */
        AssetSourceRunMutationAccepted: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetSourceRunMutationResult"];
            };
        };
        /** @description Scoped conflict page. */
        AssetConflictPageOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetConflictPage"];
            };
        };
        /** @description Governed conflict decision. */
        AssetConflictMutationOK: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssetConflictMutationResult"];
            };
        };
        /** @description Malformed request. */
        Problem400: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is missing, invalid, or insufficiently recent. */
        Problem401: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Scope or authorization is forbidden. */
        Problem403: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource was not found in the authorized scope. */
        Problem404: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Version, idempotency, or state conflict. */
        Problem409: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body exceeds the operation bound. */
        Problem413: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Content type is unsupported. */
        Problem415: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Source or Workspace backpressure rejected this request. */
        Problem429: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request failed without exposing internal detail. */
        Problem500: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Required durable or identity dependency is unavailable. */
        Problem503: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Content-Type-Options": components["headers"]["ContentTypeOptions"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                "X-Trace-ID": components["headers"]["TraceID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        WorkspaceID: components["schemas"]["UUID"];
        EnvironmentID: components["schemas"]["UUID"];
        AssetID: components["schemas"]["UUID"];
        SourceID: components["schemas"]["UUID"];
        RunID: components["schemas"]["UUID"];
        Revision: number;
        ConflictID: components["schemas"]["UUID"];
        BindingID: components["schemas"]["UUID"];
        Limit: number;
        Cursor: string;
        IdempotencyKey: string;
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        CacheControl: "no-store";
        ContentTypeOptions: "nosniff";
        ReferrerPolicy: "no-referrer";
        TraceID: components["schemas"]["TraceID"];
        ETag: string;
        Location: string;
        AuditID: components["schemas"]["UUID"];
        IdempotentReplay: "true" | "false";
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBrowserConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BrowserConfigOK"];
            503: components["responses"]["Problem503"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionOK"];
            401: components["responses"]["Problem401"];
            503: components["responses"]["Problem503"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OverviewOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                search?: string;
                service_id?: components["schemas"]["UUID"];
                kinds?: components["schemas"]["AssetKind"][];
                source_ids?: components["schemas"]["UUID"][];
                lifecycles?: components["schemas"]["AssetLifecycle"][];
                mapping_statuses?: components["schemas"]["MappingStatus"][];
                criticalities?: components["schemas"]["Criticality"][];
                data_classifications?: components["schemas"]["DataClassification"][];
                sort?: components["schemas"]["AssetSort"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetPageOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            201: components["responses"]["AssetCreated"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetDetailOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    patchAsset: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAssetRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    quarantineAsset: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionAssetRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    retireAsset: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                asset_id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionAssetRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    listAssetRelations: {
        parameters: {
            query?: {
                asset_id?: components["schemas"]["UUID"];
                source_id?: components["schemas"]["UUID"];
                types?: components["schemas"]["RelationshipType"][];
                statuses?: components["schemas"]["RelationshipStatus"][];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetRelationPageOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    listServiceAssetBindings: {
        parameters: {
            query?: {
                service_id?: components["schemas"]["UUID"];
                asset_id?: components["schemas"]["UUID"];
                roles?: components["schemas"]["BindingRole"][];
                statuses?: components["schemas"]["BindingStatus"][];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ServiceAssetBindingPageOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createServiceAssetBinding: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceAssetBindingRequest"];
            };
        };
        responses: {
            201: components["responses"]["ServiceAssetBindingCreated"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    deleteServiceAssetBinding: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                environment_id: components["parameters"]["EnvironmentID"];
                binding_id: components["parameters"]["BindingID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteServiceAssetBindingRequest"];
            };
        };
        responses: {
            204: components["responses"]["ServiceAssetBindingDeleted"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    listAssetSources: {
        parameters: {
            query?: {
                kinds?: components["schemas"]["SourceKind"][];
                statuses?: components["schemas"]["SourceStatus"][];
                gate_statuses?: components["schemas"]["SourceGateStatus"][];
                /** @description Must be supplied together with environment_id. */
                usage?: "manual_asset_create";
                /** @description Must be supplied together with usage=manual_asset_create. */
                environment_id?: components["schemas"]["UUID"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetSourcePageOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createAssetSource: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetSourceRequest"];
            };
        };
        responses: {
            201: components["responses"]["AssetSourceRevisionCreated"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    getAssetSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetSourceDetailOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createAssetSourceRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetSourceRevisionRequest"];
            };
        };
        responses: {
            201: components["responses"]["AssetSourceRevisionCreated"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    validateAssetSourceRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptySourceRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetSourceRunMutationOK"];
            202: components["responses"]["AssetSourceRunMutationAccepted"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    publishAssetSourceRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
                revision: components["parameters"]["Revision"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceReasonRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetSourceRevisionMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    disableAssetSource: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceReasonRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetSourceMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    syncAssetSource: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptySourceRequest"];
            };
        };
        responses: {
            202: components["responses"]["AssetSourceRunMutationAccepted"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createAssetSourceImport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateAssetSourceImportRequest"];
            };
        };
        responses: {
            202: components["responses"]["AssetSourceRunMutationAccepted"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    createAssetSourceIngestionBatch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                source_id: components["parameters"]["SourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["AssetSourceRunMutationAccepted"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    getAssetSourceRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetSourceRunOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    listAssetConflicts: {
        parameters: {
            query: {
                environment_id: components["schemas"]["UUID"];
                asset_id?: components["schemas"]["UUID"];
                source_id?: components["schemas"]["UUID"];
                statuses?: components["schemas"]["ConflictStatus"][];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AssetConflictPageOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
    resolveAssetConflict: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceID"];
                conflict_id: components["parameters"]["ConflictID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveAssetConflictRequest"];
            };
        };
        responses: {
            200: components["responses"]["AssetConflictMutationOK"];
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            413: components["responses"]["Problem413"];
            415: components["responses"]["Problem415"];
            500: components["responses"]["Problem500"];
            503: components["responses"]["Problem503"];
        };
    };
}
